namespace ProjectZ.Enum {
    public enum EnumClassItemTableType {

        CLASS_ITEM_TABLE_NONE = -1,

        CLASS_ITEM_TABLE_WEAPONE = 0,
        CLASS_ITEM_TABLE_HELMET,
        CLASS_ITEM_TABLE_ARMOR,
        CLASS_ITEM_TABLE_GLOVES,
        CLASS_ITEM_TABLE_SHOES,
        CLASS_ITEM_TABLE_AVATAR,
        CLASS_ITEM_TABLE_MAX,

        CLASS_ITEM_TABLE_NECKLACE = CLASS_ITEM_TABLE_MAX,
        CLASS_ITEM_TABLE_CLOAK,
        CLASS_ITEM_TABLE_RING,
        CLASS_ITEM_TABLE_CHARM,
        CLASS_ITEM_TABLE_TITLE,
        CLASS_ITEM_TABLE_CHARGE,
        CLASS_ITEM_TABLE_QUEST,
        CLASS_ITEM_TABLE_ETC,
        CLASS_ITEM_TABLE_VEHICLE,
        CLASS_ITEM_TABLE_BATTLE_PET,
        CLASS_ITEM_TABLE_FAIRY,
        CLASS_ALL_ITEM_TABLE_MAX = CLASS_ITEM_TABLE_FAIRY
    };

    enum INVEN_BAG_TYPE {
        BAG_TYPE_NORMAL = 0,
        BAG_TYPE_ACCESSORY,
        BAG_TYPE_MISC,
        BAG_TYPE_TITLE,
        BAG_TYPE_WAREHOUSE,
        BAG_TYPE_FAIRY,
        BAG_TYPE_BATTLE_PET,
        BAG_TYPE_MAX
    };
}